{% set name = "de-dip-bundestag" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7abf4205f92d599294ab3828861ec20f224ccf8b546573e7eaa0e9acb771c078

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - python >=3.6
    - python-dateutil
    - urllib3 >=1.25.3

test:
  imports:
    - deutschland.dip_bundestag
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bundesAPI/dip-bundestag-api
  summary: 'Bundestag: Dokumentations- und Informationssystem für Parlamentsmaterialien'
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
